name: Release Charts
on:
  push:
    branches:
      - main  # Change this to your default branch
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        with:
          charts_dir: .  # Change this to your charts directory
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Generate Index
        run: |
          helm repo index . 

      - name: Commit Index
        run: |
          git add index.yaml
          git commit -m "Update index.yaml"
          git push
